export const features = [
	{
		featureGroup: { id: 1, name: "Çekiş" },
		featureValueType: { id: 1, name: "Single Select Value" },
		features: [
			{ id: 1, name: "4x2(Önden Çekişli)" },
			{ id: 2, name: "4x2(Arkadan İtişli)" },
			{ id: 3, name: "4x4" },
		],
	},
	{
		featureGroup: { id: 2, name: "Yakıt" },
		featureValueType: { id: 1, name: "Single Select Value" },
		features: [
			{ id: 4, name: "Benzin" },
			{ id: 5, name: "Dizel" },
			{ id: 6, name: "Benzin&LPG" },
			{ id: 7, name: "Hibrit" },
			{ id: 8, name: "Elektrik" },
		],
	},
	{
		featureGroup: { id: 3, name: "Vites" },
		featureValueType: { id: 1, name: "Single Select Value" },
		features: [
			{ id: 9, name: "Otomatik" },
			{ id: 10, name: "Manuel" },
		],
	},
	{
		featureGroup: { id: 4, name: "Garanti" },
		featureValueType: { id: 1, name: "Single Select Value" },
		features: [
			{ id: 11, name: "Evet" },
			{ id: 12, name: "Hayır" },
		],
	},
	{
		featureGroup: { id: 5, name: "Kasa Tipi" },
		featureValueType: { id: 1, name: "Single Select Value" },
		features: [
			{ id: 13, name: "Sedan" },
			{ id: 14, name: "Hatchback" },
			{ id: 15, name: "Coupe" },
			{ id: 16, name: "SUV" },
		],
	},
];
export const categories = [
	{ id: 1, name: "SUV" },
	{ id: 2, name: "Otomobil" },
];
export const brands = [
	{
		id: 1,
		label: "Toyota",
		modeller: [
			{ id: 1, label: "Corolla" },
			{ id: 2, label: "Camry" },
			{ id: 3, label: "RAV4" },
		],
	},
	{
		id: 2,
		label: "Volkswagen",
		modeller: [
			{ id: 4, label: "Golf" },
			{ id: 5, label: "Passat" },
			{ id: 6, label: "Tiguan" },
		],
	},
	{
		id: 3,
		label: "Ford",
		modeller: [
			{ id: 7, label: "F-150" },
			{ id: 8, label: "Mustang" },
			{ id: 9, label: "Focus" },
		],
	},
	{
		id: 4,
		label: "Honda",
		modeller: [
			{ id: 10, label: "Civic" },
			{ id: 11, label: "Accord" },
			{ id: 12, label: "CR-V" },
		],
	},
	{
		id: 5,
		label: "Chevrolet",
		modeller: [
			{ id: 13, label: "Silverado" },
			{ id: 14, label: "Equinox" },
			{ id: 15, label: "Malibu" },
		],
	},
	{
		id: 6,
		label: "Nissan",
		modeller: [
			{ id: 16, label: "Altima" },
			{ id: 17, label: "Sentra" },
			{ id: 18, label: "Rogue" },
		],
	},
	{
		id: 7,
		label: "Hyundai",
		modeller: [
			{ id: 19, label: "Elantra" },
			{ id: 20, label: "Sonata" },
			{ id: 21, label: "Tucson" },
		],
	},
	{
		id: 8,
		label: "BMW",
		modeller: [
			{ id: 22, label: "3 Serisi" },
			{ id: 23, label: "5 Serisi" },
			{ id: 24, label: "X5" },
		],
	},
	{
		id: 9,
		label: "Mercedes-Benz",
		modeller: [
			{ id: 25, label: "C-Serisi" },
			{ id: 26, label: "E-Serisi" },
			{ id: 27, label: "GLC" },
		],
	},
	{
		id: 10,
		label: "Audi",
		modeller: [
			{ id: 28, label: "A3" },
			{ id: 29, label: "A4" },
			{ id: 30, label: "Q5" },
		],
	},
];
export const cars = [
	{
		marka: "Toyota",
		model: "Corolla",
		ilanBasligi: "Toyota Corolla 2021 - Az Kullanılmış",
		yil: 2021,
		km: 12000,
		renk: "Beyaz",
		fiyat: 350000,
		il: "İstanbul",
		ilce: "Kadıköy",
	},
	{
		marka: "Ford",
		model: "Focus",
		ilanBasligi: "Ford Focus 2019 - Bakımlı",
		yil: 2019,
		km: 45000,
		renk: "Mavi",
		fiyat: 250000,
		il: "Ankara",
		ilce: "Çankaya",
	},
	{
		marka: "Volkswagen",
		model: "Passat",
		ilanBasligi: "Volkswagen Passat 2018 - Full Paket",
		yil: 2018,
		km: 60000,
		renk: "Siyah",
		fiyat: 280000,
		il: "İzmir",
		ilce: "Bornova",
	},
	{
		marka: "Honda",
		model: "Civic",
		ilanBasligi: "Honda Civic 2020 - Garaj Aracı",
		yil: 2020,
		km: 10000,
		renk: "Kırmızı",
		fiyat: 330000,
		il: "Bursa",
		ilce: "Nilüfer",
	},
	{
		marka: "Renault",
		model: "Megane",
		ilanBasligi: "Renault Megane 2017 - Orijinal Parçalarla",
		yil: 2017,
		km: 70000,
		renk: "Gri",
		fiyat: 200000,
		il: "Adana",
		ilce: "Seyhan",
	},
	{
		marka: "Hyundai",
		model: "Elantra",
		ilanBasligi: "Hyundai Elantra 2022 - Sıfır Gibi",
		yil: 2022,
		km: 5000,
		renk: "Gümüş",
		fiyat: 400000,
		il: "Antalya",
		ilce: "Muratpaşa",
	},
	{
		marka: "Opel",
		model: "Astra",
		ilanBasligi: "Opel Astra 2016 - Az Kullanılmış",
		yil: 2016,
		km: 80000,
		renk: "Beyaz",
		fiyat: 180000,
		il: "Konya",
		ilce: "Selçuklu",
	},
	{
		marka: "Mercedes-Benz",
		model: "C-Class",
		ilanBasligi: "Mercedes C-Class 2021 - Lüks Paket",
		yil: 2021,
		km: 15000,
		renk: "Siyah",
		fiyat: 700000,
		il: "Kayseri",
		ilce: "Melikgazi",
	},
	{
		marka: "BMW",
		model: "3 Serisi",
		ilanBasligi: "BMW 3 Serisi 2019 - Full Donanım",
		yil: 2019,
		km: 30000,
		renk: "Mavi",
		fiyat: 650000,
		il: "Eskişehir",
		ilce: "Odunpazarı",
	},
	{
		marka: "Audi",
		model: "A4",
		ilanBasligi: "Audi A4 2018 - Konforlu",
		yil: 2018,
		km: 50000,
		renk: "Gri",
		fiyat: 500000,
		il: "Sakarya",
		ilce: "Serdivan",
	},
	{
		marka: "Kia",
		model: "Ceed",
		ilanBasligi: "Kia Ceed 2020 - Az Kullanılmış",
		yil: 2020,
		km: 18000,
		renk: "Mavi",
		fiyat: 280000,
		il: "Aydın",
		ilce: "Efeler",
	},
	{
		marka: "Nissan",
		model: "Qashqai",
		ilanBasligi: "Nissan Qashqai 2019 - Düşük KM",
		yil: 2019,
		km: 25000,
		renk: "Kırmızı",
		fiyat: 370000,
		il: "Mersin",
		ilce: "Yenişehir",
	},
	{
		marka: "Seat",
		model: "Leon",
		ilanBasligi: "Seat Leon 2020 - Full Paket",
		yil: 2020,
		km: 22000,
		renk: "Beyaz",
		fiyat: 320000,
		il: "Balıkesir",
		ilce: "Altıeylül",
	},
	{
		marka: "Skoda",
		model: "Octavia",
		ilanBasligi: "Skoda Octavia 2018 - Bakımlı",
		yil: 2018,
		km: 45000,
		renk: "Siyah",
		fiyat: 260000,
		il: "Denizli",
		ilce: "Pamukkale",
	},
	{
		marka: "Peugeot",
		model: "308",
		ilanBasligi: "Peugeot 308 2017 - Uygun Fiyat",
		yil: 2017,
		km: 55000,
		renk: "Gri",
		fiyat: 220000,
		il: "Muğla",
		ilce: "Bodrum",
	},
	{
		marka: "Citroën",
		model: "C4",
		ilanBasligi: "Citroën C4 2019 - Az Kullanılmış",
		yil: 2019,
		km: 29000,
		renk: "Gümüş",
		fiyat: 290000,
		il: "Kocaeli",
		ilce: "İzmit",
	},
	{
		marka: "Fiat",
		model: "Egea",
		ilanBasligi: "Fiat Egea 2018 - Konforlu",
		yil: 2018,
		km: 40000,
		renk: "Kırmızı",
		fiyat: 250000,
		il: "Samsun",
		ilce: "Atakum",
	},
	{
		marka: "Dacia",
		model: "Duster",
		ilanBasligi: "Dacia Duster 2021 - Yüksek Donanım",
		yil: 2021,
		km: 12000,
		renk: "Beyaz",
		fiyat: 370000,
		il: "Gaziantep",
		ilce: "Şehitkamil",
	},
	{
		marka: "Chevrolet",
		model: "Cruze",
		ilanBasligi: "Chevrolet Cruze 2016 - Orijinal Parçalarla",
		yil: 2016,
		km: 80000,
		renk: "Mavi",
		fiyat: 160000,
		il: "Trabzon",
		ilce: "Ortahisar",
	},
	{
		marka: "Mazda",
		model: "Mazda3",
		ilanBasligi: "Mazda Mazda3 2020 - Düşük KM",
		yil: 2020,
		km: 15000,
		renk: "Kırmızı",
		fiyat: 350000,
		il: "Tekirdağ",
		ilce: "Süleymanpaşa",
	},
	{
		marka: "Volvo",
		model: "S60",
		ilanBasligi: "Volvo S60 2019 - Full Paket",
		yil: 2019,
		km: 35000,
		renk: "Siyah",
		fiyat: 500000,
		il: "Aydın",
		ilce: "Didim",
	},
	{
		marka: "Jaguar",
		model: "XE",
		ilanBasligi: "Jaguar XE 2018 - Lüks Araç",
		yil: 2018,
		km: 28000,
		renk: "Gri",
		fiyat: 550000,
		il: "Hatay",
		ilce: "Defne",
	},
	{
		marka: "Land Rover",
		model: "Range Rover Evoque",
		ilanBasligi: "Land Rover Evoque 2021 - Az Kullanılmış",
		yil: 2021,
		km: 10000,
		renk: "Beyaz",
		fiyat: 850000,
		il: "Antalya",
		ilce: "Kemer",
	},
	{
		marka: "Tesla",
		model: "Model 3",
		ilanBasligi: "Tesla Model 3 2022 - Full Elektrikli",
		yil: 2022,
		km: 5000,
		renk: "Beyaz",
		fiyat: 1_200_000,
		il: "İstanbul",
		ilce: "Beşiktaş",
	},
	{
		marka: "Porsche",
		model: "Cayenne",
		ilanBasligi: "Porsche Cayenne 2021 - Lüks SUV",
		yil: 2021,
		km: 12000,
		renk: "Siyah",
		fiyat: 2_000_000,
		il: "Ankara",
		ilce: "Çankaya",
	},
	{
		marka: "Lexus",
		model: "RX",
		ilanBasligi: "Lexus RX 2020 - Full Donanım",
		yil: 2020,
		km: 20000,
		renk: "Gri",
		fiyat: 950_000,
		il: "İzmir",
		ilce: "Çiğli",
	},
	{
		marka: "Subaru",
		model: "Forester",
		ilanBasligi: "Subaru Forester 2019 - Düşük KM",
		yil: 2019,
		km: 35000,
		renk: "Mavi",
		fiyat: 420_000,
		il: "Bursa",
		ilce: "Osmangazi",
	},
	{
		marka: "Toyota",
		model: "RAV4",
		ilanBasligi: "Toyota RAV4 2022 - Sıfır Gibi",
		yil: 2022,
		km: 8000,
		renk: "Beyaz",
		fiyat: 650_000,
		il: "Adana",
		ilce: "Çukurova",
	},
	{
		marka: "Hyundai",
		model: "Santa Fe",
		ilanBasligi: "Hyundai Santa Fe 2018 - Konforlu SUV",
		yil: 2018,
		km: 60000,
		renk: "Gri",
		fiyat: 350_000,
		il: "Antalya",
		ilce: "Manavgat",
	},
	{
		marka: "Ford",
		model: "Kuga",
		ilanBasligi: "Ford Kuga 2019 - Full Paket",
		yil: 2019,
		km: 35000,
		renk: "Kırmızı",
		fiyat: 500_000,
		il: "İstanbul",
		ilce: "Üsküdar",
	},
	{
		marka: "Nissan",
		model: "X-Trail",
		ilanBasligi: "Nissan X-Trail 2018 - Bakımlı",
		yil: 2018,
		km: 45000,
		renk: "Siyah",
		fiyat: 400_000,
		il: "İstanbul",
		ilce: "Şişli",
	},
	{
		marka: "Honda",
		model: "CR-V",
		ilanBasligi: "Honda CR-V 2021 - Full Donanım",
		yil: 2021,
		km: 20000,
		renk: "Beyaz",
		fiyat: 700_000,
		il: "İstanbul",
		ilce: "Beylikdüzü",
	},
	{
		marka: "Volkswagen",
		model: "Tiguan",
		ilanBasligi: "Volkswagen Tiguan 2020 - Full Paket",
		yil: 2020,
		km: 18000,
		renk: "Gri",
		fiyat: 800_000,
		il: "İstanbul",
		ilce: "Bağcılar",
	},
	{
		marka: "Mercedes-Benz",
		model: "GLC",
		ilanBasligi: "Mercedes GLC 2021 - Lüks SUV",
		yil: 2021,
		km: 15000,
		renk: "Siyah",
		fiyat: 1_200_000,
		il: "Ankara",
		ilce: "Keçiören",
	},
	{
		marka: "BMW",
		model: "X5",
		ilanBasligi: "BMW X5 2020 - Yüksek Donanım",
		yil: 2020,
		km: 30000,
		renk: "Siyah",
		fiyat: 1_100_000,
		il: "İzmir",
		ilce: "Balçova",
	},
	{
		marka: "Audi",
		model: "Q5",
		ilanBasligi: "Audi Q5 2019 - Lüks Paket",
		yil: 2019,
		km: 32000,
		renk: "Beyaz",
		fiyat: 950_000,
		il: "Bursa",
		ilce: "Nilüfer",
	},
	{
		marka: "Volvo",
		model: "XC60",
		ilanBasligi: "Volvo XC60 2018 - Düşük KM",
		yil: 2018,
		km: 40000,
		renk: "Gri",
		fiyat: 500_000,
		il: "İstanbul",
		ilce: "Beyoğlu",
	},
	{
		marka: "Land Rover",
		model: "Discovery",
		ilanBasligi: "Land Rover Discovery 2020 - Konforlu",
		yil: 2020,
		km: 15000,
		renk: "Siyah",
		fiyat: 1_400_000,
		il: "Ankara",
		ilce: "Yenimahalle",
	},
	{
		marka: "Subaru",
		model: "Outback",
		ilanBasligi: "Subaru Outback 2018 - Bakımlı",
		yil: 2018,
		km: 50000,
		renk: "Mavi",
		fiyat: 350_000,
		il: "İstanbul",
		ilce: "Şişli",
	},
	{
		marka: "Toyota",
		model: "Highlander",
		ilanBasligi: "Toyota Highlander 2022 - Sıfır Gibi",
		yil: 2022,
		km: 8000,
		renk: "Beyaz",
		fiyat: 700_000,
		il: "İstanbul",
		ilce: "Bakırköy",
	},
	{
		marka: "Hyundai",
		model: "Palisade",
		ilanBasligi: "Hyundai Palisade 2021 - Full Paket",
		yil: 2021,
		km: 10000,
		renk: "Siyah",
		fiyat: 900_000,
		il: "Ankara",
		ilce: "Altındağ",
	},
];
